[general]
# Log level
#
# debug=5, info=4, warning=3, error=2, fatal=1, panic=0
log_level=4


# ChirpStack configuration.
[chirpstack]

  # API configuration.
  #
  # This configuration is used to automatically create the:
  #   * Device profile
  #   * Gateways
  #   * Application
  #   * Devices
  [chirpstack.api]

  # JWT token.
  #
  # API key to connect to the ChirpStack API. This API key can created within
  # the ChirpStack web-interface.
  api_key="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjaGlycHN0YWNrIiwiaXNzIjoiY2hpcnBzdGFjayIsInN1YiI6ImM2ZDdkNjEyLTdjYjEtNDMyNi1hN2FkLTljZGEyMzg3YjliYyIsInR5cCI6ImtleSJ9.RwT5ReuoeFmvzuzAb0mkCWFz4rZFxisW7bXB5OzlpCU"

  # Server.
  #
  # This must point to the API interface of ChirpStack.
  # If the server is running on the same machine, keep this to the
  # default value.
  server="127.0.0.1:8080"

  # Insecure.
  #
  # Set this to true when the endpoint is not using TLS.
  insecure=true


  # MQTT integration configuration.
  #
  # This integration is used for counting the number of uplinks that are
  # published by the ChirpStack MQTT integration.
  [chirpstack.integration.mqtt]

  # MQTT server.
  server="tcp://127.0.0.1:1883"

  # Username.
  username=""

  # Password.
  password=""


  # MQTT gateway backend.
  [chirpstack.gateway.backend.mqtt]

  # MQTT server.
  server="tcp://127.0.0.1:1883"

  # Username.
  username=""

  # Password.
  password=""


# Simulator configuration.
[[simulator]]

# Tenant ID.
#
# It is recommended to create a new tenant for simulations.
tenant_id="5933f80e-0431-47c7-9e90-569d2d49480e"

# Duration.
#
# This defines the duration of the simulation. If set to '0s', the simulation
# will run until terminated.
duration="0s"

# Activation time.
#
# This is the time that the simulator takes to activate the devices. This
# value must be less than the simulator duration.
activation_time="1m"

# Device configuration.
[simulator.device]

# Number of devices to simulate.
count=5

# Uplink interval.
uplink_interval="5m"

# FPort.
f_port=10

# Payload (HEX encoded).
payload="010203"

# Frequency (Hz).
frequency=868100000

# Bandwidth (Hz).
bandwidth=125000

# Spreading-factor.
spreading_factor=7

dev_euis = [
  "0004A30B001C0530",
  "0004A30B001C0531",
  "0004A30B001C0532",
  "0004A30B001C0533",
  "0004A30B001C0534"
]

  # Gateway configuration.
  [simulator.gateway]

  # Min number of receiving gateways.
  min_count=1

  # Max number of receiving gateways.
  max_count=1

  # Event topic template.
  event_topic_template="eu868/gateway/{{ .GatewayID }}/event/{{ .Event }}"

  # Command topic template.
  command_topic_template="eu868/gateway/{{ .GatewayID }}/command/{{ .Command }}"

[[simulator.applications]]
name = "rw-rts-monitor"

# Prometheus metrics configuration.
#
# Using Prometheus (and Grafana), it is possible to visualize various
# simulation metrics like:
#   * Join-Requests sent
#   * Join-Accepts received
#   * Uplinks sent (by the devices)
#   * Uplinks sent (by the gateways)
#   * Uplinks sent (by the ChirpStack MQTT integration)
[prometheus]

# IP:port to bind the Prometheus endpoint to.
#
# Metrics can be retrieved from /metrics.
bind="0.0.0.0:9000"
